### ISSUE TITLE
[Pikmin 1] Add support for materials

### ISSUE THREAD

**Issue by bingusgaming490** [MeltyPlayer/MeltyTool#35]
I dumped the models of Pikmin 1 with the batch file and viewed both the .fbx and .glb of models such as the Pikmin and Olimar and they don't seem to have any vertex and/or material colors 
![Screenshot 2023-12-12 070155](https://github.com/MeltyPlayer/FinModelUtility/assets/120013221/48d893be-309b-4c7d-a4a9-5ec28a8b7f72)
![Screenshot 2023-12-12 070217](https://github.com/MeltyPlayer/FinModelUtility/assets/120013221/df4fb9c6-6b81-43e0-82af-6f0843821073)

Did I do something wrong? Is this something you couldn't figure out?
I downloaded the latest repository from the source code

**Comment by MeltyPlayer** [comment]
Thanks for filing an issue!

These characters’ colors are actually specified via material shaders rather than vertex colors, and unfortunately I haven’t figured out the material format for Pikmin 1 yet.

You should be able to work around this by recreating the materials in whatever tool/engine you were hoping to import the models into. You could also just rip the models from Pikmin 2 instead (which has significantly better material support), though I believe that also specifies colors in the shader so that might also require some tinkering.
